### ISSUE TITLE
[启动崩溃]: 

### ISSUE THREAD

**Issue by Peony-white** [MuCloudOfficial/Minecraft-Crash-Helper#1]
### 确定启动器为版本最新

- [X] 我确保自己的启动器正处于最新版本

### Minecraft 游戏报错输出

![屏幕截图(8)](https://github.com/MuCloudOfficial/Minecraft-Crash-Helper/assets/159577371/8a8122d2-9a55-4ddf-a329-0bce75a0ddef)
[错误报告-2024-2-10_3.59.12.zip](https://github.com/MuCloudOfficial/Minecraft-Crash-Helper/files/14225840/-2024-2-10_3.59.12.zip)
在更新驱动前后都是这样的情况。
顺便说一下其他的情况，不知道有没有价值
本人是电脑小白，不太清楚这方面的知识，前段时间玩怪猎碰到了驱动崩溃的情况，不知道是否有关联
![屏幕截图(3)](https://github.com/MuCloudOfficial/Minecraft-Crash-Helper/assets/159577371/ef50bffa-b4c8-44f1-8283-651705365534)
当时好像是关闭了这个选项解决了问题
![20240210041212_1](https://github.com/MuCloudOfficial/Minecraft-Crash-Helper/assets/159577371/a24c1f28-bbed-4f53-bd2f-68bc8f11cdef)
在一开始并没有遇到这类的问题，在8月份左右笔记本返厂修理过一次，好像是更换主板，接着就是碰到这些情况

**Comment by Peony-white** [comment]
补充一下，原版1.19.2能够打开

**Comment by MuCloudOfficial** [comment]
__先祝你新年快乐__

---  

其次，我大概知道了事情的原因，请提供一下现在电脑里的显卡信息  

具体方法
> Windows键 + R 然后输入 dxdiag , 选择是然后等待，会出现一个界面，界面上的显示和呈现两页是你当前显卡  
> 点击保存所有信息，位置选择桌面，然后会生成一个dxdiag.txt， 把那个东西发我即可

**Comment by Peony-white** [comment]
大佬也新年快乐
[DxDiag.txt](https://github.com/MuCloudOfficial/Minecraft-Crash-Helper/files/14227896/DxDiag.txt)

**Comment by MuCloudOfficial** [comment]
已经看过了你的显卡信息，大概拯救者是吗？
如果是的话，你可以使用Legion Zone应用将显卡模式转换为独显直连模式后重试
如果你并不想这么做的话，我建议检查你AMD核心显示卡的驱动版本
最新AMD核显驱动：https://drivers.amd.com/drivers/whql-amd-software-adrenalin-edition-24.1.1-win10-win11-jan23-vega-polaris.exe

还有就是，你的电脑可能貌似被重新装过系统，如果没有legion zone的话可以从该网站获取官方最新legion zone
https://smartdl.lenovo.com.cn/lzupdate/forhome/LZSetup.exe

---

为了你的电脑使用，我的建议还是修复一下AMD的核显问题  
而且，你的电脑在显卡模式为混合模式时，如果你的设置不当，很有可能你的游戏会在核显上运行从而浪费性能  
我的建议是去 Nvidia Control Panel（英伟达显卡设置）内调整，并在Win11显示卡设置中进行调优以确保在混合模式中也可拥有最佳性能

**然而，如果你并不知道这些如何做，那么去项目主页里写的那个群里找我，我可以给你远程调优**

**Comment by Peony-white** [comment]
感谢大佬，切成独显解决了
